name: CI build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  demo1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Compiling 
        run: |
          haxelib git cpphelpers https://github.com/Vortex2Oblivion/cpphelpers
          haxelib --never git hxpy https://github.com/Vortex2Oblivion/hxpy
          cd "demos/simple example"
          haxe build.hxml
          
  demo2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Compiling 
        run: |
          haxelib git cpphelpers https://github.com/Vortex2Oblivion/cpphelpers
          haxelib --never git hxpy https://github.com/Vortex2Oblivion/hxpy
          cd "demos/reading from a file"
          haxe build.hxml
  demo3:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Compiling 
        run: |
          haxelib git cpphelpers https://github.com/Vortex2Oblivion/cpphelpers
          haxelib --never git hxpy https://github.com/Vortex2Oblivion/hxpy
          cd "demos/very high level embedding"
          haxe build.hxml

  demo4:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Compiling 
        run: |
          haxelib git cpphelpers https://github.com/Vortex2Oblivion/cpphelpers
          haxelib --never git hxpy https://github.com/Vortex2Oblivion/hxpy
          cd "demos/pure embedding"
          haxe build.hxml

  demo5:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Compiling 
        run: |
          haxelib git cpphelpers https://github.com/Vortex2Oblivion/cpphelpers
          haxelib --never git hxpy https://github.com/Vortex2Oblivion/hxpy
          cd "demos/creating a variable"
          haxe build.hxml
  
